server:
  port: 8070
spring:
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3386/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show_sql: true